### PR TITLE
Add static build

### LINKED ISSUE #7: Can't be built on many distros due to >= 3.4.0
```
    pkgconfig-depends: libarchive (==3.4.0 || >3.4.0) && <4.0
```

Is a very tight boundary. Current ubuntu LTS 18.04 cannot build this. This limits the possibilities for user-facing apps to use this library.

### PR DESCRIPTION
**Pull request by hasufell**
Fixes #7

### CODE REVIEW

**Comment by hasufell** [comment]
TODO: we need `config.h` from darwin at least... windows I don't care much

**Comment by hasufell** [comment]
Already using in ghcup: https://gitlab.haskell.org/haskell/ghcup-hs/pipelines/21900

**Comment by vmchale** [comment]
Thanks! Let me check it out; would you say it's ready for a release or so? (I suppose it's a manual flag so it won't hurt anything yet?).

**Comment by hasufell** [comment]
Yes, it's manual for now. It's possible that it has decreased functionality in the static version, since I try hard to avoid any external dependencies (and libarchive has a couple optional ones). But unpacking tar for sure works well.

**Pull request merged**
