### PR TITLE
Fix zip unpackig with bundled sources wrt #25

### PR DESCRIPTION
**Pull request by hasufell**
This adds zlib as bundled sources :sweat_smile: 

See https://github.com/vmchale/libarchive/issues/25

### CODE REVIEW

**Comment by hasufell** [comment]
@vmchale any opinion?

**Comment by vmchale** [comment]
I suppose that makes sense! Let me check what happens with zlib downstream...

**Comment by vmchale** [comment]
Ok seems to work.

**Review by vmchale — APPROVED** [review]

**Comment by hasufell** [comment]
@vmchale are you gonna make a release soon?

**Pull request merged**
